lang: es
date-format: "d 'de' MMMM 'de' yyyy"
project:
  type: book
  output-dir: docs
# Configuración de Referencias (AQUÍ ES DONDE VA)
crossref:
  fig-prefix: "Figura"
  chapters: false  


book:
  #title: "ChatGPT e Inteligencia Artificial"
  subtitle: "Programa Formativo IFCT0049"
  author: "Profesora Yamilka Toca Díaz"
  #date: "Abril 2026"
  #cover-image: "img/geralt-banner.jpg"     # Banner superior del curso
  favicon: "img/logo_uz.svg"      # Icono del sitio (pestaña)
  page-navigation: true
  navbar:
    right:
      - icon: file-pdf
        href: /chatgpt-curso.pdf
        text: "Descargar PDF"
  sidebar:
    logo: "img/logo_uz.svg"  # Logo en la barra lateral
    style: "docked"                  # Barra lateral fija
    search: true
    background: light

  #breadcrumbs: true  # elimina la navegación superior 
  chapters:
    - index.qmd
    # Grupo de información general
    - part: "Información"
      chapters:
        
        - info/info-general.qmd
        - info/guia-docente.qmd
        - info/justificacion.qmd      # Justificación y necesidad (Causas de la intervención)
        - info/objetivos-competencias.qmd # Objetivos y Competencias clave/Saberes básicos
        - info/metodologia.qmd        # Metodología (ABP y herramientas utilizadas)
        - info/calendario.qmd
    # Módulos formativos
    - part: "Módulo 1 · Fundamentos"
      chapters:
        - file: modulo1/1-introduccion-ia.qmd
          text: "1. Introducción a la Inteligencia Artificial"  
        - file: modulo1/2-tipos-ia.qmd 
          text: "2. Diferenciando Tipos de IA.qmd"
        - file: modulo1/3-funcionamiento-chatgpt.qmd
          text: "3. Funcionamiento del ChatGPT"
        - file: modulo1/4-procesamiento-nlp.qmd
          text: "4. Procesamiento del (NLP)"
        - file: modulo1/5-Entrenamiento-fine-tuning.qmd
          text: "5. Entrenamiento y Fine-tuning"
    - part: "Módulo 2 · Desafíos y Avances"
      chapters:
        - modulo2/desafios.qmd
        #- modulo2/casos.qmd
    - part: "Módulo 3 · Aplicaciones Prácticas"
      chapters:
        - modulo3/practicas.qmd
        #- modulo3/integracion.qmd
    - part: "Laboratorio y Evaluación"  # Nombre más dinámico para Innovación
      chapters:
        - practicas/lab-modulo1.qmd  # Práctica y Test del M1
        - practicas/lab-modulo2.qmd  # Práctica y Test del M2
        - practicas/lab-modulo3.qmd  # Práctica y Test del M3
        - practicas/proyecto-final.qmd # El reto que une todo 
    - recursos.qmd # Referencias bibliográficas y anexos
  page-footer: 
    left: |
      © 2026  Y. Toca – INAEM
    right: |
      Material docente protegido.  
      Licencia **CC BY-NC-SA 4.0** ![](https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png){width=80px}  
      Uso docente no comercial permitido con atribución y licencia compartida.


format:
  html:
    theme: flatly
    toc: true
    number-sections: false
    code-copy: true
    css: styles.css
    format-links: [pdf, revealjs] 
    downloads: [pdf]
  pdf:
    documentclass: scrreprt
    number-sections: true
    keep-tex: false
   



